language: python
python:
  - "3.5"
  - "3.6"

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libparted-devel
  - pip install --upgrade pip setuptools pytest
  - pip install coverage

script:
  - travis_wait env PYTHON=python3 make test coverage COVERAGE=coverage

notifications:
  email:
    on_success: change
    on_failure: change
